### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value (lldb)

### ISSUE THREAD

**Issue by rapasae** [akofman/cordova-plugin-dbmeter#6] opened 2017-07-18 10:15 UTC
Hello,
Thank you for this plugin. It works perfectly on android for me, but i've found a problem wih IOS. I can build my project with Xcode 8.2 without errors, but when I run in debug mode, I get the above message in DBMeter.swift - private func timerCallBack() - 
In release mode it simply crash.

![errorxcode](https://user-images.githubusercontent.com/20657619/28312059-0addce92-6bb2-11e7-9da6-774612817fdf.png)

I got this error after i chnaged build settings optimization to none

 because with default values i have this error while bulding:

>  was compiled with optimization - stepping may behave oddly; variables may not be available

Many thanks for your support

**Comment by akofman** [comment] 2017-10-22 17:46
I don't know what's the cause of this issue and I'm not able to reproduce it. Could you have a try with the last version of this plugin and a more recent version of XCode ?
I'm closing this issue but do not hesitate to reopen it if you're able to reproduce.

**Closed as completed by akofman** 2017-10-22 17:46 UTC
